spring:
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/ffweb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
     username: root
     password: 123456
     type: com.alibaba.druid.pool.DruidDataSource
  redis:
      host: test118
      port: 6379
      password:
  data:
    mongodb:
        uri: mongodb://looktm:looktm-test@test118:27017/watch
    elasticsearch:
        properties:
           clustername: GoldEye
           hosts: test118
           port: 9900
  rabbitmq:
     addresses: localhost
     username: guest
     password: guest
     port: 5672
     virtual-host: /
server:
    port: 8001
    tomcat.uri-encoding: UTF-8
    servlet:
      context-path: /ff
mybatis:
  #config-location: classpath:config/mybatis-config.xml
  type-aliases-package: com.gcx.api.model
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE
logging:
  level:
    com.gcx.api.dao: DEBUG
      