spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/ffweb?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: 123456
      initialize: true
      initialSize: 1
      minIdle: 3
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
   redis: 
      host: test118
      port: 6379
      password:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 10000
   data:
      #mongodb 数据库连接配置
      mongodb:
        uri: mongodb://looktm:looktm-test@test118:27017/watch
      #elasticserach 连接
      elasticsearch:
         properties:
           clustername: elastic
           hosts: test118
           port: 9300
   rabbitmq:
     addresses: localhost
     username: guest
     password: guest
     port: 5672
     virtual-host: /
custom:
   datasource:
      names: ds1
      ds1:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/nzw_city_api?useUnicode=true&characterEncoding=UTF-8&useSSL=false          
        username: root
        password: isoftadmin
mybatis:
  #config-location: classpath:config/mybatis-config.xml
  # type-aliases扫描路径
  type-aliases-package: com.gcx.api.model
  # mapper xml实现扫描路径
  mapper-locations: classpath:mapper/*.xml
  property:
    order: BEFORE
server:
    port: 8001
    contextPath: /myproject
logging:
  level:
    com.gcx.api.dao: DEBUG

elastic:
  serviceName: test118
  port: 9300
      